variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build-ui
  - build-api

build-api:
  image: docker:latest
  stage: build-api
  before_script:
    - cd ./aldrin-api/
  script:
      - >
        docker run -t --rm
        -v /var/run/docker.sock:/var/run/docker.sock
        -v "$(pwd)":"$(pwd)"
        -w "$(pwd)"
        -u 0:0
        maven:3-jdk-8
        mvn clean package -q
  after_script:
    - cd /
  artifacts:
    paths:
      - /aldrin-api/target/aldrin-0.0.1-SNAPSHOT.jar
    when: always


build-ui:
  image: node:8
  stage: build-ui
  before_script:
    - cd ./aldrin-ui/
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn install
  script:
    - yarn build
  after_script:
    - cd /

