spring:
  session:
    store-type: none
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    platform: postgres
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/Instaspring
routes:
  auth: auth
jwt:
  header: Authorization
  parameter: token
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
server:
  port: 5000