spring:
  session:
    store-type: none
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/aldrin
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      max-wait: 10000
      max-active: 20
  http:
    multipart:
      max-file-size: 8MB
  jackson:
    property-naming-strategy: SNAKE_CASE

storage:
  location: upload-dir

auth:
  privateKey: classpath:fake-privatekey.der
  publicKey: classpath:fake-publickey.der
  expiration: 604800
  headerName: Authorization

mailjet:
  publicKey: d4ae66bac27f12fe03b40223f927f941
  privateKey: 5d4d83f2bd549f47f95cd37c5ecf975d
